### ISSUE TITLE
Time cost on instruction tuning

### ISSUE THREAD

**Issue by SakuraTroyChen** [xing0047/cca-llava#3]
Hi! I am trying to reproduce the results of cca-llava. The pre-training stage worked well (9 hours on 8*A100 40G). However, the estimated time is 600 hours when it comes to the fine-tuning stage, which is unacceptable. Do you have any idea on this because it is stated in the paper that the instruction tuning takes roughly 83 hours on 4 A6000s?

**Comment by xing0047** [comment]
Hi,

Thanks for your interest in our work! 

We just tried running lora fine-tuning on one 4090 where estimated time is 137 hrs, which seems work fine (35 hrs when using 4*4090 24G). 

One possible technical reason could be mismatched installation of `xformers`. Transformers would go for eager attention implementation, which might slow down the training.

Would you mind check your attention implementation and see if this is the issue? Thanks.

**Comment by SakuraTroyChen** [comment]
Thanks for your help! After checking the installation of xformers, I strictly follow the version proposed in the pyproject.toml. The fine-tuning time decreases to 300h+. But it is still too long.
Moreover, another error comes:
`/cca-llava/llava/cca_utils/cca.py", line 429, in cca_forward
    cca_attention_mask[
RuntimeError: The expanded size of the tensor (0) must match the existing size (576) at non-singleton dimension 2.  Target sizes: [1, 0, 0].  Tensor sizes: [576, 576]`

**Comment by xing0047** [comment]
Thanks for your valuable feedback! We will check if we can reproduce this error from our side.

Also, may I check your conda env, cuda version, and training script? In such case we may check this in more detailed manner.

**Comment by SakuraTroyChen** [comment]
Thanks again for your prompt response! My environments are as follows,
pip list:
```
Package                   Version      Editable project location
------------------------- ------------ --------------------------------------------------------------
absl-py                   2.1.0
accelerate                0.21.0
aiofiles                  23.2.1
altair                    5.4.1
annotated-types           0.7.0
anyio                     4.6.2.post1
attrs                     24.2.0
bitsandbytes              0.42.0
certifi                   2022.12.7
charset-normalizer        2.1.1
click                     8.1.7
contourpy                 1.3.0
cycler                    0.12.1
deepspeed                 0.12.6
docker-pycreds            0.4.0
einops                    0.6.1
einops-exts               0.0.4
exceptiongroup            1.2.2
fastapi                   0.115.4
ffmpy                     0.4.0
filelock                  3.13.1
flash-attn                2.5.8
fonttools                 4.54.1
fsspec                    2024.2.0
gitdb                     4.0.11
GitPython                 3.1.43
gradio                    4.16.0
gradio_client             0.8.1
grpcio                    1.67.1
h11                       0.14.0
hjson                     3.1.0
httpcore                  0.17.3
httpx                     0.24.0
huggingface-hub           0.26.2
idna                      3.4
importlib_resources       6.4.5
Jinja2                    3.1.3
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
kiwisolver                1.4.7
latex2mathml              3.77.0
llava                     1.2.2.post1  /apdcephfs_qy3/share_301372554/share_info/deeponchen/cca-llava
Markdown                  3.7
markdown-it-py            3.0.0
markdown2                 2.5.1
MarkupSafe                2.1.5
matplotlib                3.9.2
mdurl                     0.1.2
mpmath                    1.3.0
narwhals                  1.12.1
networkx                  3.2.1
ninja                     1.11.1.1
numpy                     1.26.3
nvidia-cublas-cu11        11.11.3.6
nvidia-cuda-cupti-cu11    11.8.87
nvidia-cuda-nvrtc-cu11    11.8.89
nvidia-cuda-runtime-cu11  11.8.89
nvidia-cudnn-cu11         9.1.0.70
nvidia-cufft-cu11         10.9.0.58
nvidia-curand-cu11        10.3.0.86
nvidia-cusolver-cu11      11.4.1.48
nvidia-cusparse-cu11      11.7.5.86
nvidia-ml-py              12.560.30
nvidia-nccl-cu11          2.20.5
nvidia-nvtx-cu11          11.8.86
orjson                    3.10.10
packaging                 24.1
pandas                    2.2.3
peft                      0.13.2
pillow                    10.2.0
pip                       24.3.1
platformdirs              4.3.6
protobuf                  5.28.3
psutil                    6.1.0
py-cpuinfo                9.0.0
pydantic                  2.9.2
pydantic_core             2.23.4
pydub                     0.25.1
Pygments                  2.18.0
pynvml                    11.5.0
pyparsing                 3.2.0
python-dateutil           2.9.0.post0
python-multipart          0.0.17
pytz                      2024.2
PyYAML                    6.0.2
referencing               0.35.1
regex                     2024.9.11
requests                  2.28.1
rich                      13.9.3
rpds-py                   0.20.0
ruff                      0.7.1
safetensors               0.4.5
scikit-learn              1.2.2
scipy                     1.14.1
semantic-version          2.10.0
sentencepiece             0.1.99
sentry-sdk                2.17.0
setproctitle              1.3.3
setuptools                75.1.0
shellingham               1.5.4
shortuuid                 1.0.13
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
starlette                 0.41.2
svgwrite                  1.4.3
sympy                     1.13.1
tensorboard               2.18.0
tensorboard-data-server   0.7.2
threadpoolctl             3.5.0
timm                      0.6.13
tokenizers                0.15.2
tomlkit                   0.12.0
torch                     2.1.1+cu118
torchaudio                2.1.1+cu118
torchvision               0.16.1+cu118
tqdm                      4.66.6
transformers              4.37.2
triton                    2.1.0
typer                     0.12.5
typing_extensions         4.12.2
tzdata                    2024.2
urllib3                   1.26.13
uvicorn                   0.32.0
wandb                     0.18.5
wavedrom                  2.0.3.post3
websockets                11.0.3
Werkzeug                  3.1.2
wheel                     0.44.0
xformers                  0.0.23+cu118
```
The cuda version is 11.8, and the training script is your default setting.

**Comment by SakuraTroyChen** [comment]
The problem is solved. The img_token_pos could be -1 when setting the causal mask according to cca positions, so I skip the the loop. Is my operation like this correct?

**Comment by xing0047** [comment]
> The problem is solved. The img_token_pos could be -1 when setting the causal mask according to cca positions, so I skip the the loop. Is my operation like this correct?

Correct. There are text-only instruction data involved in SFT stage and concentric causal masking should not be applied in such case. I have updated `cca_forward` accordingly [here](https://github.com/xing0047/cca-llava/blob/db8d3321a6a18d27c8d8759e5f3a29378c909a08/llava/cca_utils/cca.py#L356). Thanks for pointing this out!

**Comment by ErikZ719** [comment]
Hi, I follow the default settings (pyproject.toml) to do fine tuning experiments on 3X3090 and it reports out of memory, is this normal? Pre-training works fine.
`Package                   Version      Editable project location
------------------------- ------------ -------------------------
absl-py                   2.1.0
accelerate                0.26.1
aiofiles                  23.2.1
altair                    5.4.1
annotated-types           0.7.0
anyio                     4.6.2.post1
attrs                     24.2.0
bitsandbytes              0.44.1
certifi                   2022.12.7
charset-normalizer        2.1.1
click                     8.1.7
contourpy                 1.3.0
cycler                    0.12.1
deepspeed                 0.13.1
docker-pycreds            0.4.0
einops                    0.6.1
einops-exts               0.0.4
exceptiongroup            1.2.2
fastapi                   0.115.4
ffmpy                     0.4.0
filelock                  3.13.1
flash-attn                2.5.8
fonttools                 4.54.1
fsspec                    2024.2.0
gitdb                     4.0.11
GitPython                 3.1.43
gradio                    4.16.0
gradio_client             0.8.1
grpcio                    1.67.1
h11                       0.14.0
hjson                     3.1.0
httpcore                  0.17.3
httpx                     0.24.0
huggingface-hub           0.26.2
idna                      3.4
importlib_resources       6.4.5
Jinja2                    3.1.3
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
kiwisolver                1.4.7
latex2mathml              3.77.0
llava                     1.2.2.post1  /root/zqy/cca-llava
Markdown                  3.7
markdown-it-py            3.0.0
markdown2                 2.5.1
MarkupSafe                2.1.5
matplotlib                3.9.2
mdurl                     0.1.2
mpmath                    1.3.0
narwhals                  1.12.1
networkx                  3.2.1
ninja                     1.11.1.1
numpy                     1.26.3
orjson                    3.10.11
packaging                 24.1
pandas                    2.2.3
peft                      0.13.2
pillow                    10.2.0
pip                       24.3.1
platformdirs              4.3.6
protobuf                  5.28.3
psutil                    6.1.0
py-cpuinfo                9.0.0
pydantic                  2.9.2
pydantic_core             2.23.4
pydub                     0.25.1
Pygments                  2.18.0
pynvml                    11.5.0
pyparsing                 3.2.0
python-dateutil           2.9.0.post0
python-multipart          0.0.17
pytz                      2024.2
PyYAML                    6.0.2
referencing               0.35.1
regex                     2024.9.11
requests                  2.28.1
rich                      13.9.4
rpds-py                   0.20.1
ruff                      0.7.2
safetensors               0.4.5
scikit-learn              1.2.2
scipy                     1.14.1
semantic-version          2.10.0
sentencepiece             0.1.99
sentry-sdk                2.17.0
setproctitle              1.3.3
setuptools                75.1.0
shellingham               1.5.4
shortuuid                 1.0.13
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
starlette                 0.41.2
svgwrite                  1.4.3
sympy                     1.13.1
tensorboard               2.18.0
tensorboard-data-server   0.7.2
threadpoolctl             3.5.0
timm                      0.6.13
tokenizers                0.15.2
tomlkit                   0.12.0
torch                     2.1.1+cu121
torchaudio                2.1.1+cu121
torchvision               0.16.1+cu121
tqdm                      4.66.6
transformers              4.37.2
triton                    2.1.0
typer                     0.12.5
typing_extensions         4.12.2
tzdata                    2024.2
urllib3                   1.26.13
uvicorn                   0.32.0
wandb                     0.18.5
wavedrom                  2.0.3.post3
websockets                11.0.3
Werkzeug                  3.1.1
wheel                     0.44.0
xformers                  0.0.23
`

**Comment by xing0047** [comment]
Hi @ErikZ719 

Thanks for your feedback. 

As LLaVA official repo states, if you do not have enough gpu memory for LLaVA training, please consider,

1) Use LoRA: [finetune_lora.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_lora.sh). As LLaVA indicates, 7B training can be fitted in 8-RTX3090 (I runned lora training on 4090 and seems work well). Make sure `per_device_train_batch_size`*`gradient_accumulation_steps` is the same as the provided script for best reproducibility.
    
2) Replace [`zero3.json`](https://github.com/haotian-liu/LLaVA/blob/main/scripts/zero3.json) with [`zero3_offload.json`](https://github.com/haotian-liu/LLaVA/blob/main/scripts/zero3_offload.json) which offloads some parameters to CPU RAM. This slows down the training speed.
