### ISSUE TITLE
Code for computing visual-to-instruction information flow

### ISSUE THREAD

**Issue by ErikZ719** [xing0047/cca-llava#6]
Hello author, I am now trying to get the qualitative results of Figure 1 in the paper: visualization of information flow.

Thank you very much for providing a pseudo code for computing visual-to-instruction information flow in the appendix. Would you be able to provide the full visualization code, which would be helpful for me to delve into this exciting work. Thank you.

![cca_attn](https://github.com/user-attachments/assets/2c1f9573-b6c0-49f5-8cf6-7e2697c592cd)

**Comment by xing0047** [comment]
Hi @ErikZ719 

Thanks for pointing this out. Code for computing visual-to-instruction information flow is available. Please run script below for a quick glance. 

```
bash scripts/v1_5/eval/eval.cca-llava-1.5-7b.pope.coco.adv.if_vis.sh
```

The visualisation of information flow will be saved under `outputs/pope/coco`.

For details of computing this information flow, please check line `773` ~ `777` in [cca.py](https://github.com/xing0047/cca-llava/blob/main/llava/cca_utils/cca.py), where `text_image_if` is the visualised variable.

Hope these help your further explorations.

**Comment by SakuraTroyChen** [comment]
Why do I get results that are opposite to yours when using the method you provided?
<img width="485" alt="image" src="https://github.com/user-attachments/assets/006af019-cd62-471c-96c1-ae3d7ab9b7f2" />

**Comment by xing0047** [comment]
Hi @SakuraTroyChen 

I inference with the script above and it seems work fine from my side. Would you share more details on this so that we may further investigate?

![cca-llava-1 5-7b_pope_coco_adversarial_if_vis](https://github.com/user-attachments/assets/8cc0b0a5-90c6-4943-8a08-b075df59562c)

**Comment by SakuraTroyChen** [comment]
My implementations are as follows:
```
    with torch.inference_mode():
        outputs = model.generate(
            input_ids,
            images=image_tensor.unsqueeze(0).half().cuda(),
            image_sizes=[image.size],
            do_sample=False,
            num_beams=1,
            max_new_tokens=1024,
            use_cache=True,
            return_dict_in_generate=True,
            output_attentions=True,
        )

    response_start = torch.where(input_ids == 13566)[1][0]
    img_s = torch.where(input_ids == -200)[1][0]

    attn_scores = []

    # layer-wise attention
    attn_layers = [outputs[0]["attentions"][0][layer] for layer in range(32)]

    for layer in attn_layers:
            score = layer[0, :, response_start + 2 : -1, img_s : img_s + 576]
            score = score.mean(dim=[0, 1]).reshape(24, 24)

        attn_scores.append(score)

    return attn_scores, attn_layers_weights
```

**Comment by SakuraTroyChen** [comment]
Sorry. I made a terrible mistake.

**Comment by ErikZ719** [comment]
@xing0047 ,Thank you very much. Have a good day! 👍

**Comment by xing0047** [comment]
Hi @SakuraTroyChen 
 
It is okay. Happy to see your issue has been addressed. Feel free to open discussion if you have further concern on this visualisation.

**Comment by xing0047** [comment]
Hi @ErikZ719 

Glad I have helped on this. Have a good day to you too!

Feel free to re-open this issue if further clarifications are needed.
